"""add_parcelas_to_contas_pagar

Revision ID: 8c6584332576
Revises: 5c3de58689c0
Create Date: 2026-04-07 14:59:22.706550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6584332576'
down_revision: Union[str, None] = '5c3de58689c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_pagar', sa.Column('parcela_atual', sa.Integer(), server_default='1', nullable=False))
    op.add_column('contas_pagar', sa.Column('total_parcelas', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_pagar', 'total_parcelas')
    op.drop_column('contas_pagar', 'parcela_atual')
    # ### end Alembic commands ###
