"""create tables

Revision ID: b7ec101f1d31
Revises: 
Create Date: 2026-03-01 14:44:21.283405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ec101f1d31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('ordens_producao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'em_andamento', 'concluida', name='ordemproducaostatus'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_producao_codigo'), 'ordens_producao', ['codigo'], unique=True)
    op.create_table('pecas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ordem_producao_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('pedido', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('em_fila', 'em_andamento', 'pausada', 'concluida', 'cancelada', name='pecastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['ordem_producao_id'], ['ordens_producao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pecas_codigo'), 'pecas', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pecas_codigo'), table_name='pecas')
    op.drop_table('pecas')
    op.drop_index(op.f('ix_ordens_producao_codigo'), table_name='ordens_producao')
    op.drop_table('ordens_producao')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
